development:
  adapter:  postgresql
  host: 127.0.0.1
  database: job_graph_dev
  username: ENV["db_username"] 
  password: ENV["db_password"]

production:
  adapter: postgresql
  host: 127.0.0.1
  database: job_graph_production
  username: ENV["db_username"] 
  password: ENV["db_password"]

